// <auto-generated />
using System;
using CalculadoraDosificacionHormigon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraDosificacionHormigon.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CalculadoraDosificacionHormigon.Modelo.CalculoHormigon", b =>
                {
                    b.Property<int>("CalculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Agua")
                        .HasColumnType("REAL");

                    b.Property<double>("Arena")
                        .HasColumnType("REAL");

                    b.Property<double>("Cemento")
                        .HasColumnType("REAL");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("TEXT");

                    b.Property<double>("Grava")
                        .HasColumnType("REAL");

                    b.Property<double>("RelacionAguaCemento")
                        .HasColumnType("REAL");

                    b.Property<double>("ResistenciaEstimada")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumenTotal")
                        .HasColumnType("REAL");

                    b.HasKey("CalculoId");

                    b.ToTable("CalculosHormigon");
                });
#pragma warning restore 612, 618
        }
    }
}
